"""Export what the foot-pressure view needs, beside the DIMS time series.

DIMS's time-series contract is one measure per CSV, so the sixteen individual
sensors cannot travel that way — a multi-column CSV is averaged into a single
trace, which is precisely the information this view exists to show. They go in
their own asset instead, read directly by the replacement video component.

The foot outline is generated **here**, by the same function that draws it in
the Dash dashboard (``figures._foot_outline``), so the two renderings cannot
drift apart. The browser only draws the path it is given.
"""

import json
import os

import figures
import gaitdata
from dims_adapter.export import resample, TARGET_HZ

#: Bounds of the drawing, matching the Dash figure's axes.
VIEW_BOX = [-1150, -1250, 2300, 2450]


def demographics_for(info):
    """The subject panel, as label/value rows — the same rows the Dash app shows."""
    def number(value, unit="", digits=0):
        return "—" if value is None else f"{value:.{digits}f}{unit}"

    rows = [
        ("Group", info.group_label),
        ("Study", info.study_label),
        ("Age", number(info.age, " years")),
        ("Sex", info.gender_label),
        ("Height / weight", f"{number(info.height, ' m', 2)} / {number(info.weight, ' kg')}"),
        ("Hoehn & Yahr", number(info.hoehnyahr, "", 1) if info.grp == 1 else "n/a"),
        ("UPDRS", number(info.updrs) if info.grp == 1 else "n/a"),
        ("Stride time", number(info.stride_median, " s", 2)),
        ("Stride-time variability", number(info.stride_cv, "%", 1)),
    ]
    return [{"label": label, "value": value} for label, value in rows]


def export_feet(conn, subject, out_dir, target_hz=TARGET_HZ):
    """Write ``{subject}_feet.json``: the sensor field over time, plus context."""
    info = gaitdata.subject_info(conn, subject)
    frame = resample(
        gaitdata.traces_between(conn, subject, 0.0, info.duration), target_hz
    )

    payload = {
        "subject": subject,
        "t": [round(float(v), 3) for v in frame["t"]],
        "sensors": {
            s: [round(float(v), 1) for v in frame[s]] for s in gaitdata.SENSORS
        },
        "coords": {s: list(gaitdata.SENSOR_COORDS[s]) for s in gaitdata.SENSORS},
        "left": gaitdata.LEFT_SENSORS,
        "right": gaitdata.RIGHT_SENSORS,
        # Generated by the same function the Dash dashboard draws with.
        "outlines": [
            figures._foot_outline(-500, mirror=False),
            figures._foot_outline(500, mirror=True),
        ],
        # Fixes the colour scale for the whole recording. Without it the scale
        # re-fits every frame and the same colour means a different force.
        "peak": float(info.sensor_peak),
        "viewBox": VIEW_BOX,
        "colors": {"left": figures.LEFT_COLOR, "right": figures.RIGHT_COLOR},
        "scale": [[stop, color] for stop, color in figures.PRESSURE_SCALE],
        "demographics": demographics_for(info),
        "label": info.label,
    }

    path = os.path.join(out_dir, f"{subject}_feet.json")
    with open(path, "w") as handle:
        json.dump(payload, handle, separators=(",", ":"))
    return path, len(payload["t"])
